BUNDLES = [
    "//protocols/whisper/app:onos-protocols-whisper-app",
    "//protocols/whisper/api:onos-protocols-whisper-api",
    "//protocols/whisper/datamodel:onos-protocols-whisper-datamodel",
    "//providers/whisper:onos-providers-whisper",
]


onos_app(
    category = "Utility",
    included_bundles = BUNDLES,
    required_apps = ["org.onosproject.hostprovider","org.onosproject.null","org.onosproject.whisper"],
    app_name = "org.onosproject.whisper",
    description = "Whisper Application for ONOS",
    title = "Whisper Protocol App",
    url = "http://idlab.org",
)
